org: domenicrincon
service: alerta-utec

provider:
  name: aws
  runtime: python3.12
   # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::758228479217:role/LabRole	
  environment:
    TABLE_NAME: ${sls:stage}-WebSocketConnections
    
functions:
  wsConnect:
    handler: web_socket.ws_connect
    events:
      - websocket:
          route: $connect

  wsDisconnect:
    handler: web_socket.ws_disconnect
    events:
      - websocket:
          route: $disconnect

  wsSendMessage:
    handler: web_socket.ws_send_message
    events:
      - websocket:
          route: sendMessage

  wsBroadcastUpdate:
    handler: web_socket.ws_broadcast_update
    events:
      - websocket:
          route: broadcastUpdate

resources:
  Resources:
    WebSocketConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST


